
GET http://localhost/api/task

###

POST http://localhost/api/task
Content-Type: application/json

{
  "title": "Json title",
  "description": "Json description "
}

###

POST http://localhost/api/task
Content-Type: application/x-www-form-urlencoded

title=httpTitle&description=httpDescription

###

GET http://localhost/api/task/1

###

PUT http://localhost/api/task/1
Content-Type: application/json

{
  "title": "Update title",
  "description": "Update description"
}

###

DELETE http://localhost/api/task/1

